//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Game
{
    public Board Board { get; set; }
    private Random _r;

    public Game()
    {
        Board = new Board();
        _r = new Random();
        PlayerBlack = new Player(Board.StartBlack);
        PlayerWhite = new Player(Board.StartWhite);
    }

    public void Next()
    {
        PlayerWhite.TakeTurn();
    }

    

	public virtual Player PlayerWhite
	{
		get;
		set;
	}

	public virtual Player PlayerBlack
	{
		get;
		set;
	}

}

