//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Player
{
    private Random _r;



    public List<Pawn> Pawns { get; set; }

    public Field StartField { get; set; }

    public Player(Field startField)
    {
        this.StartField = startField;
        Pawns = new List<Pawn>();
        Pawns.Add(new Pawn()
        {
            Field = startField;
        });
        _r = new Random();
    }

    public void TakeTurn()
    {
        int diceThrow = _r.Next(0, 4);
        Pawn pawn = Pawns.FirstOrDefault();

        pawn.Move(diceThrow);
        Field theField = pawn.Field;

        for(int i = 0; i < diceThrow; i++)
        {
            theField = theField.NextField;
        }

        pawn.Field = theField;
    }
}

