//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Views
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class DigitView
	{
		public virtual void ShowValue(int w)
		{
            int digit = w;
            switch (digit)
            {
                case 1:
                    Console.WriteLine("1");
                case 2:
                    Console.WriteLine("2");
                case 3:
                    Console.WriteLine("3");
                case 4:
                    Console.WriteLine("4");
                case 5:
                    Console.WriteLine("5");
                case 6:
                    Console.WriteLine("6");
                default:
                    Console.WriteLine("Impossible digit!");
                    break;
            }
		}

	}
}

