//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Views
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class InputView
	{
		public virtual void AskForInput()
		{
			throw new System.NotImplementedException();
		}

		public virtual void ShowEnd()
		{
			throw new System.NotImplementedException();
		}

	}
}

