//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Dice
	{
		public virtual int Throw()
		{
			//throw new System.NotImplementedException();
            Random randomGenerator = new Random();
            int w = randomGenerator.Next(6) + 1;
            return w;
		}

	}
}

